version: '3.8'

services:

    core-db:
        restart: always
        networks:
            - core-private

    core-app:
        restart: always
        networks:
            - core-private

    core-web:
        restart: always
        networks:
            - proycer-public
            - core-private

networks:
    core-private:
    proycer-public:
        external: true